# Generated by Django 2.1.1 on 2019-01-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0002_member_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(max_length=300),
        ),
    ]
