# Generated by Django 2.1.1 on 2019-01-01 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('repay_amount', models.PositiveIntegerField()),
                ('interest_rate', models.PositiveIntegerField()),
                ('remaining_principal', models.PositiveIntegerField()),
                ('remaining_interest', models.PositiveIntegerField()),
                ('remaining_fine', models.PositiveIntegerField()),
                ('granted_date', models.DateField()),
                ('duration_months', models.PositiveIntegerField()),
                ('granter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granter', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collection.Bank')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loan.Loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('amount_paid', models.PositiveIntegerField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loan.Loan')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collection.WorkingMonth')),
            ],
        ),
    ]
